import { useEffect, useState } from "react";
import type { HubGameManifest } from "p2play-core";
import { formatHubGameLabel } from "p2play-core";

export type HubCatalogGame = HubGameManifest & {
  label: string;
  /** From games.json via download-games.js — used for live-add quick examples. */
  repo?: string;
};

interface GamesCatalogFile {
  games: Array<HubGameManifest & { repo?: string }>;
}

function catalogUrl(): string {
  const rawBase = import.meta.env.BASE_URL || "./";
  const base = rawBase.endsWith("/") ? rawBase : `${rawBase}/`;
  return `${base}games/catalog.json`;
}

/**
 * Loads Hub game picker entries from public/games/catalog.json
 * (generated by download-games.js from each game's hub-manifest.json).
 */
export function useGamesCatalog() {
  const [games, setGames] = useState<HubCatalogGame[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      try {
        setLoading(true);
        setError(null);
        const res = await fetch(catalogUrl(), { cache: "no-store" });
        if (!res.ok) {
          throw new Error(`Impossible de charger le catalogue de jeux (HTTP ${res.status}).`);
        }
        const data = (await res.json()) as GamesCatalogFile;
        if (!Array.isArray(data.games)) {
          throw new Error("catalog.json invalide: champ games manquant.");
        }
        const mapped = data.games.map((g) => ({
          ...g,
          label: formatHubGameLabel(g),
          repo: typeof g.repo === "string" ? g.repo : undefined,
        }));
        if (!cancelled) setGames(mapped);
      } catch (err) {
        if (!cancelled) {
          setGames([]);
          setError(err instanceof Error ? err.message : "Erreur catalogue jeux.");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
  }, []);

  return { games, loading, error };
}
